
//get all journeys
//GET http://localhost:3001/api/v1/journeys/getAll


// get specific journey
 //GET http://localhost:3001/api/v1/journeys/2


// get all stations
//GET http://localhost:3001/api/v1/stations/getAll?search=Baana

// get a single  station
 // GET http://localhost:3001/api/v1/stations/98